### ISSUE TITLE
Some methods are not working after upgrading to 1.0

### ISSUE THREAD

**Issue by ronin** [heroku/platform-api#62]
I have problems with couple of api methods after upgrading to 1.0.0. For now I've noticed this issue only for `addon` resource:

```ruby
client = PlatformAPI.connect_oauth(ENV["HEROKU_TOKEN"])
client.addon.list_by_app("some-app-name")
NoMethodError: undefined method `addon' for #<Heroics::Client url="https://api.heroku.com">
	from /Users/ronin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/heroics-0.0.21/lib/heroics/client.rb:30:in `method_missing'
	from /Users/ronin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/platform-api-1.0.0/lib/platform-api/client.rb:839:in `list_by_app'
```

The same problem occurs for `list` and `info`. Is there any new way to invoke those methods or is it just a bug?

**Comment by djcp** [comment]
@ronin #61 will fix this and should be merged and deployed soon - sorry for the inconvenience!

**Comment by djcp** [comment]
Sorry for the delay - this method (and other add-on related methods) should be working now in version 1.0.1
